# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- vra-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-tidy

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: news/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: valleyroad # jekyll-seo-tag > Owners twitter username
author: valleyroad # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: VRA # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/valleyroad
    - https://www.facebook.com/valleyroad
    - https://www.linkedin.com/in/valleyroad
    - https://github.com/valleyroad
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Regina # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Recent News # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    feature_text: ""
    feature_image: "assets/img/news.jpg"
  businesses:
    title: Businesses # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    feature_text: ""
    feature_image: "assets/img/businesses.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Valley Road Association" # Site name or title, also used in jekyll-seo-tag
logo: "assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Valley Road Association is a resilient community of businesses located
on Valley Road in Saskatoon. We invite you to take a trip just off Circle Drive South
to explore all of the unique shops and activities along the scenic Saskatchewan River!" # Site description and default description, also used in jekyll-seo-tag
url: "https://valley-road.github.io" # Site url, also used in jekyll-seo-tag
baseurl: "/assoc-web/"
repo: ""
email: "webmaster@valleyroad.com"
mapbox_key: pk.eyJ1IjoidGhlc2hrYSIsImEiOiJjazdhMHU1c2sweXY4M2twajN6Mm5tc3UxIn0.ufehUlXtj97Y14450O4YDg
# disqus: "" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: 'assets/logos/logo@16px.png'
  32: 'assets/logos/logo@32px.png'
  96: 'assets/logos/logo@96px.png'
  120: 'assets/logos/logo@120px.png'
  144: 'assets/logos/logo@144px.png'
  180: 'assets/logos/logo@180px.png'
  512: 'assets/logos/logo@512px.png'
  1024: 'assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: About Us
  url: /about/
- title: Businesses
  url: /businesses/
- title: Members
  url: /members/
- title: News
  url: /news/
- title: Contact
  url: /contact/
- title: Search
  url: /search/

navigation_footer:
- title: "&quot;Valley Road &mdash; Naturally Great.&quot;"
  url: 

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/valleyroad
  LinkedIn: https://www.linkedin.com/in/valleyroad
  GitHub: https://github.com/valleyroad
  link: https://valleyroad.ca
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
